name: Build, Push Docker Image & Deploy with Terraform

on:
    push:
        branches: ["main"]
    workflow_dispatch:
    
jobs:
    deploy:
        name: Build and deploy container image
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Step 2: Log in to Docker Hub
            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

            # Step 3: Build and push Docker image
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                context: ./code-base/website
                file: ./code-base/website/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/my-ecs-demo-image:latest
             

            # Step 4: Push Docker image
            - name: Push Docker image
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/my-ecs-demo-image:latest

            # Step 5: Set up Terraform
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.8.5

            # Step 6: Initialize Terraform
            - name: Terraform Init
              run: terraform init
              working-directory: ./infrastructure

            # Step 7: Apply Terraform configuration
            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: ./infrastructure
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: us-east-1
                


